sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - 6.9.5
before_install:
  - npm i -g npm
before_script:
  - npm prune
after_success:

  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/